openapi: 3.0.0
info:
  title: Nistrax API Swagger
  description: Nistrax API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://nistrax-api.merovision.com
    description: server
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Superadmin
  - name: Superadmin > Auth
  - name: Superadmin > User
  - name: Superadmin > Company
  - name: Superadmin > Tenant/Company User
  - name: Admin
  - name: Admin > Auth
  - name: Admin > Category
paths:
  /api/v1/superadmin/auth/login:
    post:
      tags:
        - Superadmin > Auth
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: superadmin@nistrax.com
                password:
                  type: string
                  example: password
      security:
        - noauthAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/superadmin/auth/logout:
    post:
      tags:
        - Superadmin > Auth
      summary: logout user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: superadmin@nistrax.com
                password:
                  type: string
                  example: password
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/superadmin/auth/me:
    get:
      tags:
        - Superadmin > User
      summary: show about logged in user
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/superadmin/tenants:
    post:
      tags:
        - Superadmin > Company
      summary: store company data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Nistrax
                email:
                  type: string
                  example: nistrax@gmail.com
                phone_no:
                  type: integer
                  example: '4656567'
                vat_pan_no:
                  type: integer
                  example: '45646546'
                address:
                  type: string
                  example: Birtamode
                established_year:
                  type: integer
                  example: '2026'
                website_link:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Superadmin > Company
      summary: show all company list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '15'
        - name: search_keyword
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/superadmin/tenants/{id}:
    post:
      tags:
        - Superadmin > Company
      summary: update company/tenant data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Nistrax
                email:
                  type: string
                  example: nistrax@gmail.com
                phone_no:
                  type: integer
                  example: '4656567'
                vat_pan_no:
                  type: integer
                  example: '45646546'
                address:
                  type: string
                  example: Birtamode
                established_year:
                  type: integer
                  example: '2026'
                website_link:
                  type: string
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/superadmin/tenants/nistrax/users:
    get:
      tags:
        - Superadmin > Tenant/Company User
      summary: show company user
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/superadmin/tenants/{slug}/users:
    post:
      tags:
        - Superadmin > Tenant/Company User
      summary: store company user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Hy
                email:
                  type: string
                  example: nitesh@gmail.com
                password:
                  type: string
                  example: password
                role:
                  type: string
                  example: admin
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Superadmin > Tenant/Company User
      summary: delete company user
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/auth/login:
    post:
      tags:
        - Admin > Auth
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: hy@gmail.com
                password:
                  type: string
                  example: password
      security:
        - noauthAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/auth/me:
    get:
      tags:
        - Admin > Auth
      summary: show about logged in user
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/categories:
    post:
      tags:
        - Admin > Category
      summary: store category data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Soft Drinks
                parent_category_id: 1
                description: Carbonated and non-carbonated soft drinks
                icon: ti-bottle
                is_active: true
                sort_order: 1
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Category
      summary: show all category data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
        - name: pagination_limit
          in: query
          schema:
            type: string
        - name: search_keyword
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/categories/{id}:
    post:
      tags:
        - Admin > Category
      summary: update category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Beverages
                parent_category_id: null
                description: All types of drinks and beverages
                icon: ti-cup
                is_active: true
                sort_order: 1
                _method: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Category
      summary: delete category
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/admin/categories/{slug}:
    get:
      tags:
        - Admin > Category
      summary: single show category data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Tenant
          in: header
          schema:
            type: string
          example: nistrax
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
